---
language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq
  - ln -s ansible-role-newrelic ../Aplyca.NewRelic

install:
  # Install Ansible.
  - sudo pip install -r tests/requirements.txt

script:
  - tests/test.sh

notifications:
  email: false
