---
- name: Add the New Relic package repo to yum
  become: yes
  yum:
    name: http://download.newrelic.com/pub/newrelic/el5/i386/newrelic-repo-5-3.noarch.rpm
    state: present

- name: Install New Relic with yum
  become: yes
  yum:
    name: newrelic-sysmond
    state: present
